from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyCalculator import Ui_Dialog
import math

# Create application 
app = QtWidgets.QApplication(sys.argv)
    
# Create form and init UI
Dialog = QtWidgets.QDialog()
ui = Ui_Dialog()
ui.setupUi(Dialog)
Dialog.show()

# Hook logic
global entryNumberDec

def setText(str):
    ui.textEdit.setText(str)

def bp(key):
    calcEntry = ui.textEdit.toPlainText()
    setText(calcEntry + key)
    try:
        if key == "=": 
            result = eval(calcEntry.replace("=", ""))
            setText(str(result))
        elif key == "C":
            ui.textEdit.clear()
        elif key == "←":
            setText(calcEntry[0:-1])
        elif key == "sin":
            setText(str(math.sin(math.radians(float(eval(calcEntry))))))
        elif key == "cos":
            setText(str(math.cos(math.radians(float(eval(calcEntry))))))
        elif key == "tg":
            setText(str(math.tan(math.radians(float(eval(calcEntry))))))
        elif key == "√":
            setText(str(math.sqrt(float(eval(calcEntry)))))
        elif key == "!":
            setText(str(math.factorial(float(eval(calcEntry)))))
    except:
        setText("Error!")

def bin_to_dec(digit):
    dlina=len(digit)
    chislo_dec=0
    for i in range(0, dlina):
        chislo_dec=chislo_dec+int(digit[i])*(2**(dlina-i-1))
    return chislo_dec

def lcdChange():
    try:
        if ui.radioButton_2.isChecked():
            ui.lcdNumber.display(int(ui.textEdit.toPlainText()))
            ui.lcdNumber_2.display(int(ui.textEdit.toPlainText()))
            ui.lcdNumber_3.display(int(ui.textEdit.toPlainText()))
            ui.lcdNumber_4.display(int(ui.textEdit.toPlainText()))
        elif ui.radioButton.isChecked():
            entryNumberDec = bin_to_dec(ui.textEdit.toPlainText())
            ui.lcdNumber.display(int(entryNumberDec))
            ui.lcdNumber_2.display(int(entryNumberDec))
            ui.lcdNumber_3.display(int(entryNumberDec))
            ui.lcdNumber_4.display(int(entryNumberDec))
        elif ui.radioButton_3.isChecked():
            entryNumberDec = int(ui.textEdit.toPlainText(), 16)
            ui.lcdNumber.display(int(entryNumberDec))
            ui.lcdNumber_2.display(int(entryNumberDec))
            ui.lcdNumber_3.display(int(entryNumberDec))
            ui.lcdNumber_4.display(int(entryNumberDec))
        elif ui.radioButton_4.isChecked():
            entryNumberDec = int(ui.textEdit.toPlainText(), 8)
            ui.lcdNumber.display(int(entryNumberDec))
            ui.lcdNumber_2.display(int(entryNumberDec))
            ui.lcdNumber_3.display(int(entryNumberDec))
            ui.lcdNumber_4.display(int(entryNumberDec))
    except:
        ui.lcdNumber.display(int(0))
        ui.lcdNumber_2.display(int(0))
        ui.lcdNumber_3.display(int(0))
        ui.lcdNumber_4.display(int(0)) 


def onRadioButtonClickedBin():
    ui.textEdit.clear()
    ui.pushButton_8.setEnabled(True)
    ui.pushButton_8.setStyleSheet("background : white; ")
    ui.pushButton_3.setEnabled(True)
    ui.pushButton_3.setStyleSheet("background : white; ")
    ui.pushButton.setEnabled(False)
    ui.pushButton.setStyleSheet("background : silver; ")
    ui.pushButton_20.setEnabled(False)
    ui.pushButton_20.setStyleSheet("background : silver; ")
    ui.pushButton_29.setEnabled(False)
    ui.pushButton_29.setStyleSheet("background : silver; ")
    ui.pushButton_30.setEnabled(False)
    ui.pushButton_30.setStyleSheet("background : silver; ")
    ui.pushButton_31.setEnabled(False)
    ui.pushButton_31.setStyleSheet("background : silver; ")
    ui.pushButton_32.setEnabled(False)
    ui.pushButton_32.setStyleSheet("background : silver; ")
    ui.pushButton_33.setEnabled(False)
    ui.pushButton_33.setStyleSheet("background : silver; ")
    ui.pushButton_6.setEnabled(False)
    ui.pushButton_6.setStyleSheet("background : silver; ")
    ui.pushButton_7.setEnabled(False)
    ui.pushButton_7.setStyleSheet("background : silver; ")
    ui.pushButton_10.setEnabled(False)
    ui.pushButton_10.setStyleSheet("background : silver; ")
    ui.pushButton_11.setEnabled(False)
    ui.pushButton_11.setStyleSheet("background : silver; ")
    ui.pushButton_12.setEnabled(False)
    ui.pushButton_12.setStyleSheet("background : silver; ")
    ui.pushButton_14.setEnabled(False)
    ui.pushButton_14.setStyleSheet("background : silver; ")
    ui.pushButton_15.setEnabled(False)
    ui.pushButton_15.setStyleSheet("background : silver; ")
    ui.pushButton_16.setEnabled(False)
    ui.pushButton_16.setStyleSheet("background : silver; ")
    ui.pushButton_26.setEnabled(False)
    ui.pushButton_26.setStyleSheet("background : silver; ")
    ui.pushButton_27.setEnabled(False)
    ui.pushButton_27.setStyleSheet("background : silver; ")
    ui.pushButton_28.setEnabled(False)
    ui.pushButton_28.setStyleSheet("background : silver; ")
    ui.pushButton_35.setEnabled(False)
    ui.pushButton_35.setStyleSheet("background : silver; ")
    ui.pushButton_36.setEnabled(False)
    ui.pushButton_36.setStyleSheet("background : silver; ")

def onRadioButtonClickedDec():
    ui.textEdit.clear()
    ui.pushButton_8.setEnabled(True)
    ui.pushButton_8.setStyleSheet("background : white; ")
    ui.pushButton_3.setEnabled(True)
    ui.pushButton_3.setStyleSheet("background : white; ")
    ui.pushButton.setEnabled(True)
    ui.pushButton.setStyleSheet("background : white; ")
    ui.pushButton_20.setEnabled(False)
    ui.pushButton_20.setStyleSheet("background : silver; ")
    ui.pushButton_29.setEnabled(False)
    ui.pushButton_29.setStyleSheet("background : silver; ")
    ui.pushButton_30.setEnabled(False)
    ui.pushButton_30.setStyleSheet("background : silver; ")
    ui.pushButton_31.setEnabled(False)
    ui.pushButton_31.setStyleSheet("background : silver; ")
    ui.pushButton_32.setEnabled(False)
    ui.pushButton_32.setStyleSheet("background : silver; ")
    ui.pushButton_33.setEnabled(False)
    ui.pushButton_33.setStyleSheet("background : silver; ")
    ui.pushButton_6.setEnabled(True)
    ui.pushButton_6.setStyleSheet("background : white; ")
    ui.pushButton_7.setEnabled(True)
    ui.pushButton_7.setStyleSheet("background : white; ")
    ui.pushButton_10.setEnabled(True)
    ui.pushButton_10.setStyleSheet("background : white; ")
    ui.pushButton_11.setEnabled(True)
    ui.pushButton_11.setStyleSheet("background : white; ")
    ui.pushButton_12.setEnabled(True)
    ui.pushButton_12.setStyleSheet("background : white; ")
    ui.pushButton_14.setEnabled(True)
    ui.pushButton_14.setStyleSheet("background : white; ")
    ui.pushButton_15.setEnabled(True)
    ui.pushButton_15.setStyleSheet("background : white; ")
    ui.pushButton_16.setEnabled(True)
    ui.pushButton_16.setStyleSheet("background : white; ")
    ui.pushButton_26.setEnabled(True)
    ui.pushButton_26.setStyleSheet("background : white; ")
    ui.pushButton_27.setEnabled(True)
    ui.pushButton_27.setStyleSheet("background : white; ")
    ui.pushButton_28.setEnabled(True)
    ui.pushButton_28.setStyleSheet("background : white; ")
    ui.pushButton_35.setEnabled(True)
    ui.pushButton_35.setStyleSheet("background : white; ")
    ui.pushButton_36.setEnabled(True)
    ui.pushButton_36.setStyleSheet("background : white; ")

def onRadioButtonClickedHex():
    ui.textEdit.clear()
    ui.pushButton_8.setEnabled(True)
    ui.pushButton_8.setStyleSheet("background : white; ")
    ui.pushButton_3.setEnabled(True)
    ui.pushButton_3.setStyleSheet("background : white; ")
    ui.pushButton.setEnabled(False)
    ui.pushButton.setStyleSheet("background : silver; ")
    ui.pushButton_20.setEnabled(True)
    ui.pushButton_20.setStyleSheet("background : white; ")
    ui.pushButton_29.setEnabled(True)
    ui.pushButton_29.setStyleSheet("background : white; ")
    ui.pushButton_30.setEnabled(True)
    ui.pushButton_30.setStyleSheet("background : white; ")
    ui.pushButton_31.setEnabled(True)
    ui.pushButton_31.setStyleSheet("background : white; ")
    ui.pushButton_32.setEnabled(True)
    ui.pushButton_32.setStyleSheet("background : white; ")
    ui.pushButton_33.setEnabled(True)
    ui.pushButton_33.setStyleSheet("background : white; ")
    ui.pushButton_6.setEnabled(True)
    ui.pushButton_6.setStyleSheet("background : white; ")
    ui.pushButton_7.setEnabled(True)
    ui.pushButton_7.setStyleSheet("background : white; ")
    ui.pushButton_10.setEnabled(True)
    ui.pushButton_10.setStyleSheet("background : white; ")
    ui.pushButton_11.setEnabled(True)
    ui.pushButton_11.setStyleSheet("background : white; ")
    ui.pushButton_12.setEnabled(True)
    ui.pushButton_12.setStyleSheet("background : white; ")
    ui.pushButton_14.setEnabled(True)
    ui.pushButton_14.setStyleSheet("background : white; ")
    ui.pushButton_15.setEnabled(True)
    ui.pushButton_15.setStyleSheet("background : white; ")
    ui.pushButton_16.setEnabled(True)
    ui.pushButton_16.setStyleSheet("background : white; ")
    ui.pushButton_26.setEnabled(False)
    ui.pushButton_26.setStyleSheet("background : silver; ")
    ui.pushButton_27.setEnabled(False)
    ui.pushButton_27.setStyleSheet("background : silver; ")
    ui.pushButton_28.setEnabled(False)
    ui.pushButton_28.setStyleSheet("background : silver; ")
    ui.pushButton_35.setEnabled(False)
    ui.pushButton_35.setStyleSheet("background : silver; ")
    ui.pushButton_36.setEnabled(False)
    ui.pushButton_36.setStyleSheet("background : silver; ")

def onRadioButtonClickedOct():
    ui.textEdit.clear()
    ui.pushButton_8.setEnabled(True)
    ui.pushButton_8.setStyleSheet("background : white; ")
    ui.pushButton_3.setEnabled(True)
    ui.pushButton_3.setStyleSheet("background : white; ")
    ui.pushButton.setEnabled(False)
    ui.pushButton.setStyleSheet("background : silver; ")
    ui.pushButton_20.setEnabled(False)
    ui.pushButton_20.setStyleSheet("background : silver; ")
    ui.pushButton_29.setEnabled(False)
    ui.pushButton_29.setStyleSheet("background : silver; ")
    ui.pushButton_30.setEnabled(False)
    ui.pushButton_30.setStyleSheet("background : silver; ")
    ui.pushButton_31.setEnabled(False)
    ui.pushButton_31.setStyleSheet("background : silver; ")
    ui.pushButton_32.setEnabled(False)
    ui.pushButton_32.setStyleSheet("background : silver; ")
    ui.pushButton_33.setEnabled(False)
    ui.pushButton_33.setStyleSheet("background : silver; ")
    ui.pushButton_6.setEnabled(True)
    ui.pushButton_6.setStyleSheet("background : white; ")
    ui.pushButton_7.setEnabled(True)
    ui.pushButton_7.setStyleSheet("background : white; ")
    ui.pushButton_10.setEnabled(True)
    ui.pushButton_10.setStyleSheet("background : white; ")
    ui.pushButton_11.setEnabled(True)
    ui.pushButton_11.setStyleSheet("background : white; ")
    ui.pushButton_12.setEnabled(True)
    ui.pushButton_12.setStyleSheet("background : white; ")
    ui.pushButton_14.setEnabled(False)
    ui.pushButton_14.setStyleSheet("background : silver; ")
    ui.pushButton_15.setEnabled(False)
    ui.pushButton_15.setStyleSheet("background : silver; ")
    ui.pushButton_16.setEnabled(True)
    ui.pushButton_16.setStyleSheet("background : white; ")
    ui.pushButton_26.setEnabled(False)
    ui.pushButton_26.setStyleSheet("background : silver; ")
    ui.pushButton_27.setEnabled(False)
    ui.pushButton_27.setStyleSheet("background : silver; ")
    ui.pushButton_28.setEnabled(False)
    ui.pushButton_28.setStyleSheet("background : silver; ")
    ui.pushButton_35.setEnabled(False)
    ui.pushButton_35.setStyleSheet("background : silver; ")
    ui.pushButton_36.setEnabled(False)
    ui.pushButton_36.setStyleSheet("background : silver; ")

# button bind
ui.textEdit.textChanged.connect(lcdChange)
ui.radioButton.toggled.connect(onRadioButtonClickedBin)
ui.radioButton_2.toggled.connect(onRadioButtonClickedDec)
ui.radioButton_3.toggled.connect(onRadioButtonClickedHex)
ui.radioButton_4.toggled.connect(onRadioButtonClickedOct)

ui.pushButton_3.clicked.connect(lambda: bp("0"))
ui.pushButton_8.clicked.connect(lambda: bp("1"))
ui.pushButton_7.clicked.connect(lambda: bp("2"))
ui.pushButton_6.clicked.connect(lambda: bp("3"))
ui.pushButton_12.clicked.connect(lambda: bp("4"))
ui.pushButton_11.clicked.connect(lambda: bp("5"))
ui.pushButton_10.clicked.connect(lambda: bp("6"))
ui.pushButton_16.clicked.connect(lambda: bp("7"))
ui.pushButton_15.clicked.connect(lambda: bp("8"))
ui.pushButton_14.clicked.connect(lambda: bp("9"))
ui.pushButton_9.clicked.connect(lambda: bp("+"))
ui.pushButton_13.clicked.connect(lambda: bp("-"))
ui.pushButton_23.clicked.connect(lambda: bp("*"))
ui.pushButton_24.clicked.connect(lambda: bp("/"))
ui.pushButton_2.clicked.connect(lambda: bp("="))
ui.pushButton_34.clicked.connect(lambda: bp("C"))
ui.pushButton_21.clicked.connect(lambda: bp("("))
ui.pushButton_22.clicked.connect(lambda: bp(")"))
ui.pushButton_25.clicked.connect(lambda: bp("←"))
ui.pushButton_26.clicked.connect(lambda: bp("tg"))
ui.pushButton_27.clicked.connect(lambda: bp("cos"))
ui.pushButton_28.clicked.connect(lambda: bp("sin"))
ui.pushButton_36.clicked.connect(lambda: bp("√"))
ui.pushButton_35.clicked.connect(lambda: bp("!"))
ui.pushButton_20.clicked.connect(lambda: bp("A"))
ui.pushButton_29.clicked.connect(lambda: bp("B"))
ui.pushButton_30.clicked.connect(lambda: bp("c"))
ui.pushButton_31.clicked.connect(lambda: bp("D"))
ui.pushButton_32.clicked.connect(lambda: bp("E"))
ui.pushButton_33.clicked.connect(lambda: bp("F"))
ui.pushButton.clicked.connect(lambda: bp("."))

# Run main loop
sys.exit(app.exec_())