# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Development\Python\Lab5\PyCalculator.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(402, 618)
        Dialog.setStyleSheet("QPushButton {\n"
"background : white; \n"
"color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background : silver; \n"
"}\n"
"\n"
"QDialog{\n"
"    background : black;\n"
"}")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 381, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setGeometry(QtCore.QRect(20, 20, 351, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("")
        self.textEdit.setObjectName("textEdit")
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_20.setEnabled(False)
        self.pushButton_20.setGeometry(QtCore.QRect(20, 200, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setStyleSheet("background : silver;")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_29 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_29.setEnabled(False)
        self.pushButton_29.setGeometry(QtCore.QRect(80, 200, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_29.setFont(font)
        self.pushButton_29.setStyleSheet("background : silver;")
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_30 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_30.setEnabled(False)
        self.pushButton_30.setGeometry(QtCore.QRect(140, 200, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_30.setFont(font)
        self.pushButton_30.setStyleSheet("background : silver;")
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_31 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_31.setEnabled(False)
        self.pushButton_31.setGeometry(QtCore.QRect(200, 200, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_31.setFont(font)
        self.pushButton_31.setStyleSheet("background : silver;")
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_32 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_32.setEnabled(False)
        self.pushButton_32.setGeometry(QtCore.QRect(260, 200, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_32.setFont(font)
        self.pushButton_32.setStyleSheet("background : silver;")
        self.pushButton_32.setObjectName("pushButton_32")
        self.pushButton_33 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_33.setEnabled(False)
        self.pushButton_33.setGeometry(QtCore.QRect(320, 200, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_33.setFont(font)
        self.pushButton_33.setStyleSheet("background : silver;")
        self.pushButton_33.setObjectName("pushButton_33")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(20, 110, 51, 17))
        self.radioButton.setStyleSheet("background : black; color: white;")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setEnabled(True)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 130, 51, 17))
        self.radioButton_2.setTabletTracking(False)
        self.radioButton_2.setStyleSheet("background : black; color: white;")
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_3.setGeometry(QtCore.QRect(20, 150, 51, 17))
        self.radioButton_3.setStyleSheet("background : black; color: white;")
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_4.setGeometry(QtCore.QRect(20, 170, 51, 17))
        self.radioButton_4.setStyleSheet("background : black; color: white;")
        self.radioButton_4.setObjectName("radioButton_4")
        self.lcdNumber = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber.setDigitCount(20)
        self.lcdNumber.setGeometry(QtCore.QRect(193, 110, 181, 23))
        self.lcdNumber.setStyleSheet("background : black;")
        self.lcdNumber.setMode(QtWidgets.QLCDNumber.Bin)
        self.lcdNumber.setProperty("value", 0.0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_2.setDigitCount(20)
        self.lcdNumber_2.setGeometry(QtCore.QRect(193, 130, 181, 23))
        self.lcdNumber_2.setStyleSheet("background : black;")
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_3.setDigitCount(20)
        self.lcdNumber_3.setGeometry(QtCore.QRect(193, 150, 181, 23))
        self.lcdNumber_3.setStyleSheet("background : black;")
        self.lcdNumber_3.setMode(QtWidgets.QLCDNumber.Hex)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_4.setDigitCount(20)
        self.lcdNumber_4.setGeometry(QtCore.QRect(193, 170, 181, 23))
        self.lcdNumber_4.setStyleSheet("background : black;")
        self.lcdNumber_4.setMode(QtWidgets.QLCDNumber.Oct)
        self.lcdNumber_4.setProperty("value", 0.0)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(240, 560, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(320, 500, 71, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(80, 560, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(240, 500, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(160, 500, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Dialog)
        self.pushButton_8.setGeometry(QtCore.QRect(80, 500, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Dialog)
        self.pushButton_9.setGeometry(QtCore.QRect(320, 440, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(Dialog)
        self.pushButton_10.setGeometry(QtCore.QRect(240, 440, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(Dialog)
        self.pushButton_11.setGeometry(QtCore.QRect(160, 440, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(Dialog)
        self.pushButton_12.setGeometry(QtCore.QRect(80, 440, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(Dialog)
        self.pushButton_13.setGeometry(QtCore.QRect(320, 380, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(Dialog)
        self.pushButton_14.setGeometry(QtCore.QRect(240, 380, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(Dialog)
        self.pushButton_15.setGeometry(QtCore.QRect(160, 380, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setStyleSheet("")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(Dialog)
        self.pushButton_16.setGeometry(QtCore.QRect(80, 380, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setStyleSheet("")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_21 = QtWidgets.QPushButton(Dialog)
        self.pushButton_21.setGeometry(QtCore.QRect(80, 320, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setStyleSheet("")
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(Dialog)
        self.pushButton_22.setGeometry(QtCore.QRect(160, 320, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setStyleSheet("")
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(Dialog)
        self.pushButton_23.setGeometry(QtCore.QRect(240, 320, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setStyleSheet("")
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(Dialog)
        self.pushButton_24.setGeometry(QtCore.QRect(320, 320, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setStyleSheet("")
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(Dialog)
        self.pushButton_25.setGeometry(QtCore.QRect(80, 260, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_25.setFont(font)
        self.pushButton_25.setStyleSheet("")
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = QtWidgets.QPushButton(Dialog)
        self.pushButton_26.setGeometry(QtCore.QRect(0, 360, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_26.setFont(font)
        self.pushButton_26.setStyleSheet("")
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_27 = QtWidgets.QPushButton(Dialog)
        self.pushButton_27.setGeometry(QtCore.QRect(0, 310, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setStyleSheet("")
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(Dialog)
        self.pushButton_28.setGeometry(QtCore.QRect(0, 260, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_28.setFont(font)
        self.pushButton_28.setStyleSheet("")
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_34 = QtWidgets.QPushButton(Dialog)
        self.pushButton_34.setGeometry(QtCore.QRect(240, 260, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_34.setFont(font)
        self.pushButton_34.setStyleSheet("")
        self.pushButton_34.setObjectName("pushButton_34")
        self.pushButton_35 = QtWidgets.QPushButton(Dialog)
        self.pushButton_35.setGeometry(QtCore.QRect(0, 460, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_35.setFont(font)
        self.pushButton_35.setStyleSheet("")
        self.pushButton_35.setObjectName("pushButton_35")
        self.pushButton_36 = QtWidgets.QPushButton(Dialog)
        self.pushButton_36.setGeometry(QtCore.QRect(0, 410, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_36.setFont(font)
        self.pushButton_36.setStyleSheet("")
        self.pushButton_36.setObjectName("pushButton_36")


        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "PyCalculator"))
        self.groupBox.setTitle(_translate("Dialog", "Result"))
        self.pushButton_20.setText(_translate("Dialog", "A"))
        self.pushButton_29.setText(_translate("Dialog", "B"))
        self.pushButton_30.setText(_translate("Dialog", "C"))
        self.pushButton_31.setText(_translate("Dialog", "D"))
        self.pushButton_32.setText(_translate("Dialog", "E"))
        self.pushButton_33.setText(_translate("Dialog", "F"))
        self.radioButton.setText(_translate("Dialog", "BIN"))
        self.radioButton_2.setText(_translate("Dialog", "DEC"))
        self.radioButton_3.setText(_translate("Dialog", "HEX"))
        self.radioButton_4.setText(_translate("Dialog", "OCT"))
        self.pushButton.setText(_translate("Dialog", "."))
        self.pushButton_2.setText(_translate("Dialog", "="))
        self.pushButton_3.setText(_translate("Dialog", "0"))
        self.pushButton_6.setText(_translate("Dialog", "3"))
        self.pushButton_7.setText(_translate("Dialog", "2"))
        self.pushButton_8.setText(_translate("Dialog", "1"))
        self.pushButton_9.setText(_translate("Dialog", "+"))
        self.pushButton_10.setText(_translate("Dialog", "6"))
        self.pushButton_11.setText(_translate("Dialog", "5"))
        self.pushButton_12.setText(_translate("Dialog", "4"))
        self.pushButton_13.setText(_translate("Dialog", "-"))
        self.pushButton_14.setText(_translate("Dialog", "9"))
        self.pushButton_15.setText(_translate("Dialog", "8"))
        self.pushButton_16.setText(_translate("Dialog", "7"))
        self.pushButton_21.setText(_translate("Dialog", "("))
        self.pushButton_22.setText(_translate("Dialog", ")"))
        self.pushButton_23.setText(_translate("Dialog", "X"))
        self.pushButton_24.setText(_translate("Dialog", "/"))
        self.pushButton_25.setText(_translate("Dialog", "←"))
        self.pushButton_26.setText(_translate("Dialog", "tg"))
        self.pushButton_27.setText(_translate("Dialog", "cos"))
        self.pushButton_28.setText(_translate("Dialog", "sin"))
        self.pushButton_34.setText(_translate("Dialog", "C"))
        self.pushButton_35.setText(_translate("Dialog", "!"))
        self.pushButton_36.setText(_translate("Dialog", "√"))